### PR TITLE
Update Adaptor.js

### PR DESCRIPTION
**Pull request by github4maninder**
Remove '.' typo after a JSON log on line 196.

### CODE REVIEW

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
Hi @github4maninder , thanks for opening this. I think we should make the same change on [line 84](https://github.com/OpenFn/language-primero/blob/80d237ba95041527fe0e1d2c5f82ec91b058b935/src/Adaptor.js#L84) to remain consistent. Thoughts?

Also, please ensure that the adaptor is "built" using `npm run build`. you'll see that this creates an output in `lib` which you can use to test your changes.

**Comment by github4maninder** [comment]
thank you for the update. i will fix line 84 and work on npm run bulid as well.

**Comment by github4maninder** [comment]
I have updated the changes and ran the "built" using npm run built. look forward for merging this PR.
thanks 👍🏻

**Comment by taylordowns2000** [comment]
@github4maninder , this is great but it looks like your `package-lock.json` uses `lockfileVersion: 2` and `main` uses `1`. while this will get cleaned up in the release process before anything gets sent to NPM or used on OpenFn.org, I'd love to avoid introducing unwanted changes via that big package-lock diff.

Do you know how to generate v1 package-lock files? My guess is that main is using npm v6 and that's the trick. if this doesn't work out, please feel free to drop the `package-lock.json` entirely and I'll merge your changes. thanks again for the PR.

And just in case you're curious... since we have devs contributing from lots of different environments and these packages are often used by specific applications (rather than just being used by OpenFn/core or OpenFn/devtools, they're often consumed by the iPaaS at OpenFn.org) we have provided a standard-cross-platform specification in the `.devcontainer` folder. If you open this repo in VSCode, you'll actually get the option to do all your development inside a standard docker container.

When I enter that devcontainer, I see these versions:
```js
node ➜ /workspaces/language-primero (main ✗) $ node --version
v14.17.6
node ➜ /workspaces/language-primero (main ✗) $ npm --version
6.14.15
```

**Comment by github4maninder** [comment]
dropped the package-lock.json file. thank you for your advise to look inside the .devcontainer this will certainly help me not to avoid cross-platform specifications issue. I really appreciate your advise.

**Comment by taylordowns2000** [comment]
Ah sorry, I actually meant to drop it from the PR rather than delete the file. As it currently stands, the PR would _remove_ this file from the `main` branch of the repo, and we don't want that. Apologies for the unclear language.

I think the best thing you could do would be to rebase `OpenFn:main` and then only select the two files you're intending to modify: `src/Adaptor.js` and `lib/Adaptor.js`

**Comment by github4maninder** [comment]
thanks, i have update it. 
kindly check

**Comment by github4maninder** [comment]
thank you 🥇

**Pull request merged**
