### PR TITLE
Add support for query forms in the primero adaptor

### PR DESCRIPTION
**Pull request by mtuchi**
## Any notes for the reviewer ?
I have added the `getForms` helper function with it's appropriate docstring and update readme with an example. The function get the list of all forms that are accessible to this user. The user can filter the form list by record type and module.
## Related issue
Fixes # 41
## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] If needed, I've updated the changelog
- [x] I have tested my code 
- [x] I have updated read me

### CODE REVIEW

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
hey @mtuchi , the adaptor code here looks great, but I don't like your 6000 lines of changes to the `package-lock.json` - is this because of an NPM version? is it intentional? should we be using lockfileVersion 2 instead of 1?

(if not, please don't include those changes in the PR.)

**Comment by mtuchi** [comment]
> hey @mtuchi , the adaptor code here looks great, but I don't like your 6000 lines of changes to the `package-lock.json` - is this because of an NPM version? is it intentional? should we be using lockfileVersion 2 instead of 1?
> 
> (if not, please don't include those changes in the PR.)



> hey @mtuchi , the adaptor code here looks great, but I don't like your 6000 lines of changes to the `package-lock.json` - is this because of an NPM version? is it intentional? should we be using lockfileVersion 2 instead of 1?
> 
> (if not, please don't include those changes in the PR.)

@taylordowns2000 `npm install` updated the `package-lock.json` fil, my current node version is `16.17.0`. Should I down grade my node version to see if it won't update `package-lock.json` file ?

**Comment by mtuchi** [comment]
> Fixed 532737b



> hey @mtuchi , the adaptor code here looks great, but I don't like your 6000 lines of changes to the `package-lock.json` - is this because of an NPM version? is it intentional? should we be using lockfileVersion 2 instead of 1?
> 
> (if not, please don't include those changes in the PR.)

**Review by taylordowns2000 — APPROVED** [review]

**Comment by mtuchi** [comment]
Fixes #41

**Pull request merged**
